# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 22:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meem',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('meme_id', models.CharField(default=uuid.uuid4, max_length=36)),
                ('template', models.CharField(max_length=64)),
                ('sourceimgs', models.TextField()),
                ('context', models.CharField(max_length=32)),
                ('gen_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
