# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import memeviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meem',
            name='meme_id',
            field=models.CharField(default=memeviewer.models.struuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meem',
            name='number',
            field=models.IntegerField(default=memeviewer.models.next_meme_number),
        ),
    ]
