# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0002_auto_20170824_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordMeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=64)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookMeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterMeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem')),
            ],
        ),
    ]
