# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0004_auto_20170824_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.IntegerField()),
                ('image_name', models.CharField(max_length=64)),
                ('context', models.CharField(max_length=32)),
            ],
        ),
    ]
