# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0006_auto_20170824_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('context', models.CharField(default=None, max_length=32, null=True)),
                ('bg_color', models.CharField(default=None, max_length=16, null=True)),
                ('bg_img', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemeTemplateSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('rotate', models.IntegerField(default=0)),
                ('mask', models.BooleanField(default=False)),
                ('blur', models.BooleanField(default=False)),
                ('grayscale', models.BooleanField(default=False)),
                ('cover', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeTemplate')),
            ],
        ),
    ]
