# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0007_memetemplate_memetemplateslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplateslot',
            name='slot_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='h',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='w',
            field=models.PositiveIntegerField(),
        ),
    ]
