# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0008_auto_20170824_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='meem',
            name='template_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeTemplate'),
        ),
        migrations.AddField(
            model_name='memetemplateslot',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
