# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0009_auto_20170824_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeContext',
            fields=[
                ('short_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='memetemplate',
            name='context',
        ),
        migrations.AddField(
            model_name='imageincontext',
            name='context_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext'),
        ),
        migrations.AddField(
            model_name='meem',
            name='context_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext'),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='contexts',
            field=models.ManyToManyField(to='memeviewer.MemeContext'),
        ),
    ]
