# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0010_auto_20170824_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memetemplateslot',
            name='disabled',
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
