# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0016_imageincontext_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageincontext',
            name='context',
        ),
    ]
