# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0017_remove_imageincontext_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplate',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_color',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_img',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='memeviewer.MemeContext'),
        ),
    ]
