# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0019_auto_20170903_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordcommand',
            name='fun_name',
        ),
    ]
