# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0020_remove_discordcommand_fun_name'),
    ]

    database_operations = [
        migrations.AlterModelTable('DiscordServer', 'discordbot_discordserver'),
        migrations.AlterModelTable('DiscordCommand', 'discordbot_discordcommand')
    ]

    state_operations = [
        migrations.DeleteModel('DiscordServer'),
        migrations.DeleteModel('DiscordCommand'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
