# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0021_auto_20170908_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'verbose_name': 'Access token'},
        ),
        migrations.AlterModelOptions(
            name='discordmeem',
            options={'verbose_name': 'Discord meme link'},
        ),
        migrations.AlterModelOptions(
            name='facebookmeem',
            options={'verbose_name': 'Facebook meme link'},
        ),
        migrations.AlterModelOptions(
            name='imageincontext',
            options={'verbose_name': 'Queued image'},
        ),
        migrations.AlterModelOptions(
            name='meem',
            options={'verbose_name': 'Meme'},
        ),
        migrations.AlterModelOptions(
            name='memecontext',
            options={'verbose_name': 'Context'},
        ),
        migrations.AlterModelOptions(
            name='memetemplate',
            options={'verbose_name': 'Template'},
        ),
        migrations.AlterModelOptions(
            name='memetemplateslot',
            options={'verbose_name': 'Template slot'},
        ),
        migrations.AlterModelOptions(
            name='twittermeem',
            options={'verbose_name': 'Twitter meme link'},
        ),
    ]
