# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import memeviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0022_auto_20170908_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.TextField(verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='discordmeem',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem', verbose_name='Meme link'),
        ),
        migrations.AlterField(
            model_name='discordmeem',
            name='server',
            field=models.CharField(max_length=64, verbose_name='Server link'),
        ),
        migrations.AlterField(
            model_name='facebookmeem',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem', verbose_name='Meme link'),
        ),
        migrations.AlterField(
            model_name='facebookmeem',
            name='post',
            field=models.CharField(max_length=40, verbose_name='Post link'),
        ),
        migrations.AlterField(
            model_name='imageincontext',
            name='context_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext', verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='imageincontext',
            name='image_name',
            field=models.CharField(max_length=64, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='imageincontext',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'Template'), (1, 'Source Image')], verbose_name='Image type'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='context_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext', verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='gen_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date generated'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='meme_id',
            field=models.CharField(default=memeviewer.models.struuid4, max_length=36, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='number',
            field=models.IntegerField(default=memeviewer.models.next_meme_number, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='sourceimgs',
            field=models.TextField(verbose_name='Source images'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='template_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeTemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='memecontext',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='memecontext',
            name='short_name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_color',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_img',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='contexts',
            field=models.ManyToManyField(blank=True, to='memeviewer.MemeContext', verbose_name='Contexts'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='blur',
            field=models.BooleanField(default=False, verbose_name='Blur'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='cover',
            field=models.BooleanField(default=False, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='grayscale',
            field=models.BooleanField(default=False, verbose_name='Grayscale'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='mask',
            field=models.BooleanField(default=False, verbose_name='Mask'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='rotate',
            field=models.IntegerField(default=0, verbose_name='Rotation'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='slot_order',
            field=models.IntegerField(verbose_name='Slot order'),
        ),
        migrations.AlterField(
            model_name='memetemplateslot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeTemplate', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='twittermeem',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem', verbose_name='Meme link'),
        ),
        migrations.AlterField(
            model_name='twittermeem',
            name='post',
            field=models.CharField(max_length=40, verbose_name='Post link'),
        ),
    ]
