# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0025_memesourceimageoverride_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memesourceimageoverride',
            name='disabled',
        ),
        migrations.AddField(
            model_name='memesourceimageoverride',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
        migrations.AddField(
            model_name='memesourceimageoverride',
            name='friendly_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Friendly name'),
        ),
    ]
