# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0026_auto_20170929_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesourceimageoverride',
            name='friendly_name',
            field=models.CharField(default='', max_length=64, verbose_name='Friendly name'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_img',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Background image'),
        ),
    ]
