# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('memeviewer', '0029_auto_20170930_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemeSourceImageOverride',
            new_name='MemeSourceImage',
        ),
        migrations.AlterModelOptions(
            name='memesourceimage',
            options={'verbose_name': 'Source image'},
        ),
    ]
