# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0030_auto_20170930_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memetemplate',
            name='disabled',
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
