# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0031_auto_20170930_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplate',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Friendly name'),
        ),
    ]
