# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0032_memetemplate_friendly_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeSourceImageInSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem', verbose_name='Meme')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeTemplateSlot', verbose_name='Template slot')),
            ],
            options={
                'verbose_name': 'Source image in slot',
            },
        ),
    ]
