# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0033_memesourceimageinslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesourceimageinslot',
            name='source_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeSourceImage', verbose_name='Source image'),
            preserve_default=False,
        ),
    ]
