# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0034_memesourceimageinslot_source_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meem',
            name='sourceimgs',
        ),
    ]
