# Generated by Django 2.0 on 2018-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0035_remove_meem_sourceimgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesourceimage',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='File name'),
        ),
    ]
