# Generated by Django 2.0 on 2018-02-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0036_auto_20180108_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
