# Generated by Django 2.0 on 2018-02-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0037_delete_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
