# Generated by Django 2.0 on 2018-02-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0038_delete_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecontext',
            name='short_name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
