# Generated by Django 2.0 on 2018-02-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('memeviewer', '0039_auto_20180225_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecontext',
            old_name='short_name',
            new_name='context_id',
        ),
    ]
