# Generated by Django 2.0 on 2018-02-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('memeviewer', '0040_auto_20180225_2047'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='memecontext',
        #     old_name='context_id',
        #     new_name='short_name',
        # ),
    ]
