# Generated by Django 2.0 on 2018-02-27 19:47

from django.db import migrations, models
import memeviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0042_memetemplate_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplate',
            name='name',
            field=models.CharField(default=memeviewer.models.struuid4, max_length=64, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
