# Generated by Django 2.0 on 2018-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0043_auto_20180227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='memetemplate',
            name='bg_image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='C:\\Users\\morchv\\Documents\\PycharmProjects\\lamdabotweb\\media\\lambdabot\\templates'),
        ),
    ]
