# Generated by Django 2.0 on 2018-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0044_memetemplate_bg_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesourceimage',
            name='image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='C:\\Users\\morchv\\Documents\\PycharmProjects\\lamdabotweb\\media\\lambdabot\\sourceimg'),
        ),
    ]
