# Generated by Django 2.0 on 2018-02-27 20:50

from django.db import migrations, models
import memeviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0046_auto_20180227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesourceimage',
            name='name',
            field=models.CharField(default=memeviewer.models.struuid4, max_length=256, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
