# Generated by Django 2.0 on 2018-02-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0050_auto_20180228_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memetemplate',
            name='bg_img',
        ),
    ]
