# Generated by Django 2.0 on 2018-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0051_remove_memetemplate_bg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_image_file',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='lambdabot/templates/'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='image_file',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='lambdabot/templates/'),
        ),
    ]
