# Generated by Django 2.0 on 2018-03-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0052_auto_20180320_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memetemplateslot',
            name='mask',
        ),
        migrations.AddField(
            model_name='meem',
            name='source_images',
            field=models.TextField(default='[]', verbose_name='Source images'),
            preserve_default=False,
        ),
    ]
