# Generated by Django 2.0 on 2018-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0054_auto_20180321_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplateslot',
            name='slot_order',
            field=models.IntegerField(choices=[(0, 'Blue'), (1, 'Yellow'), (2, 'Green'), (3, 'Red'), (4, 'Cyan'), (5, 'Orange'), (6, 'Lime'), (7, 'Pink'), (8, 'Purple'), (9, 'Brown'), (10, 'Black'), (11, 'White')], verbose_name='Slot flavor'),
        ),
    ]
