# Generated by Django 2.0 on 2018-03-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0055_auto_20180321_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memesourceimageinslot',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='memesourceimageinslot',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='memesourceimageinslot',
            name='source_image',
        ),
        migrations.DeleteModel(
            name='MemeSourceImageInSlot',
        ),
    ]
