# Generated by Django 2.0 on 2018-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0056_auto_20180321_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_image_file',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='lambdabot/templates/', verbose_name='Template background'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='image_file',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='lambdabot/templates/', verbose_name='Template overlay'),
        ),
    ]
