# Generated by Django 2.0 on 2018-03-21 17:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0057_auto_20180321_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18, verbose_name='Background color'),
        ),
    ]
