# Generated by Django 2.0 on 2018-03-21 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0058_auto_20180321_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesourceimage',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last changed'),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last changed'),
        ),
    ]
