# Generated by Django 2.0 on 2018-03-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0060_memecontext_recent_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontext',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is public?'),
        ),
    ]
