# Generated by Django 2.0 on 2018-03-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0061_memecontext_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='memecontext',
            name='meme_count',
            field=models.IntegerField(default=0, verbose_name='Generated memes'),
        ),
    ]
