# Generated by Django 2.0 on 2018-03-23 18:17

from django.db import migrations, models
import memeviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0063_auto_20180323_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meem',
            name='number',
            field=models.IntegerField(default=memeviewer.models.next_meme_number, unique=True, verbose_name='Number'),
        ),
    ]
