# Generated by Django 2.0 on 2018-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0064_auto_20180323_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesourceimage',
            name='meme_count',
            field=models.IntegerField(default=0, verbose_name='Memes'),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='meme_count',
            field=models.IntegerField(default=0, verbose_name='Memes'),
        ),
    ]
