# Generated by Django 2.0 on 2018-03-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0065_auto_20180323_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meem',
            name='context_link',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.SET_DEFAULT, to='memeviewer.MemeContext', verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='meem',
            name='template_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memeviewer.MemeTemplate', verbose_name='Template'),
        ),
    ]
