# Generated by Django 2.0 on 2018-03-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0066_auto_20180323_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeContextCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.IntegerField()),
                ('image_name', models.CharField(max_length=256)),
                ('count', models.IntegerField(default=0)),
                ('context_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext')),
            ],
        ),
    ]
