# Generated by Django 2.0 on 2018-03-23 22:21

from django.db import migrations, models
import memeviewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0067_memecontextcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memetemplate',
            name='name',
            field=models.CharField(default=memeviewer.models.struuid4, max_length=256, primary_key=True, serialize=False, verbose_name='Unique ID'),
        ),
    ]
