# Generated by Django 2.0 on 2018-03-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0068_auto_20180323_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeSourceImageInContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued', models.BooleanField(default=False)),
                ('random_usages', models.IntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeSourceImage')),
            ],
        ),
        migrations.CreateModel(
            name='MemeTemplateInContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued', models.BooleanField(default=False)),
                ('random_usages', models.IntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeTemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='imageincontext',
            name='context_link',
        ),
        migrations.RemoveField(
            model_name='memecontextcounter',
            name='context_link',
        ),
        migrations.DeleteModel(
            name='ImageInContext',
        ),
        migrations.DeleteModel(
            name='MemeContextCounter',
        ),
        migrations.AlterUniqueTogether(
            name='memetemplateincontext',
            unique_together={('image', 'context')},
        ),
        migrations.AlterUniqueTogether(
            name='memesourceimageincontext',
            unique_together={('image', 'context')},
        ),
    ]
