# Generated by Django 2.0 on 2018-03-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0069_auto_20180324_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecontext',
            name='recent_threshold',
            field=models.IntegerField(default=10, verbose_name='Recent threshold'),
        ),
    ]
