# Generated by Django 2.0 on 2018-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0070_auto_20180324_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meem',
            options={'ordering': ['-number'], 'verbose_name': 'Meme'},
        ),
        migrations.AddIndex(
            model_name='meem',
            index=models.Index(fields=['number'], name='idx_meme_number'),
        ),
        migrations.AddIndex(
            model_name='meem',
            index=models.Index(fields=['gen_date'], name='idx_meme_gendate'),
        ),
        migrations.AddIndex(
            model_name='memecontext',
            index=models.Index(fields=['meme_count'], name='idx_context_mcount'),
        ),
        migrations.AddIndex(
            model_name='memesourceimageincontext',
            index=models.Index(fields=['context', 'random_usages'], name='memeviewer__context_973fad_idx'),
        ),
        migrations.AddIndex(
            model_name='memetemplateincontext',
            index=models.Index(fields=['context', 'random_usages'], name='memeviewer__context_8f074b_idx'),
        ),
        migrations.AddIndex(
            model_name='memetemplateslot',
            index=models.Index(fields=['template', 'slot_order'], name='idx_template_slot'),
        ),
    ]
