# Generated by Django 2.0 on 2018-03-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0072_auto_20180324_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memecontext',
            name='meme_count',
        ),
        migrations.RemoveField(
            model_name='memesourceimage',
            name='meme_count',
        ),
        migrations.RemoveField(
            model_name='memetemplate',
            name='meme_count',
        ),
        migrations.AddField(
            model_name='memesourceimageincontext',
            name='all_usages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memetemplateincontext',
            name='all_usages',
            field=models.IntegerField(default=0),
        ),
    ]
