# Generated by Django 2.0 on 2018-04-23 17:06

from django.db import migrations, models
from memeviewer.models import MemeSourceImage, MemeTemplate


def fix_paths(*_):
    for i in MemeSourceImage.objects.all():
        i.image_file = i.image_file.name.replace('lambdabot/', '')
        i.save()
    for i in MemeTemplate.objects.all():
        i.image_file = i.image_file.name.replace('lambdabot/', '')
        i.bg_image_file = i.bg_image_file.name.replace('lambdabot/', '')
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0075_auto_20180330_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesourceimage',
            name='image_file',
            field=models.ImageField(max_length=256, upload_to='sourceimg/'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='bg_image_file',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='templates/', verbose_name='Template background'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='image_file',
            field=models.ImageField(blank=True, default=None, max_length=256, null=True, upload_to='templates/', verbose_name='Template overlay'),
        ),
        migrations.RunPython(fix_paths),
    ]
