# Generated by Django 2.0 on 2018-04-27 19:41

from django.db import migrations


def do_stuff(apps, schema_editor):
    MemeImagePool = apps.get_model('memeviewer', 'MemeImagePool')
    MemeSourceImage = apps.get_model('memeviewer', 'MemeSourceImage')
    MemeTemplate = apps.get_model('memeviewer', 'MemeTemplate')
    Meem = apps.get_model('memeviewer', 'Meem')
    hldcreated = False
    hldpool = None
    halflifecreated = False
    halflifepool = None
    for i in list(MemeSourceImage.objects.all()) + list(MemeTemplate.objects.all()):
        hldcontext = i.contexts.filter(short_name='hldiscord').first()
        if hldcontext:
            if not hldcreated:
                hldpool, _ = MemeImagePool.objects.get_or_create(name='hldiscord')
                hldcreated = True
            i.image_pool = hldpool
        elif type(i) == MemeSourceImage:
            if not halflifecreated:
                halflifepool, _ = MemeImagePool.objects.get_or_create(name='halflife')
                halflifecreated = True
            i.image_pool = halflifepool
        if type(i) == MemeSourceImage:
            i.random_usages = Meem.objects.filter(source_images__contains='"' + i.name + '"').count()
        else:
            i.random_usages = i.meem_set.count()
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0077_auto_20180427_2139'),
    ]

    operations = [
        migrations.RunPython(do_stuff)
    ]
