# Generated by Django 2.0 on 2018-04-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0079_auto_20180427_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemeContext',
        ),
    ]
