# Generated by Django 2.0 on 2018-04-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0080_delete_memecontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeimagepool',
            name='friendly_name',
        ),
    ]
