# Generated by Django 2.0 on 2018-04-28 22:45

from django.db import migrations


def do_stuff(apps, schema_editor):
    MemeImagePool = apps.get_model('memeviewer', 'MemeImagePool')
    MemeTemplate = apps.get_model('memeviewer', 'MemeTemplate')
    DiscordChannel = apps.get_model('discordbot', 'DiscordChannel')
    FacebookPage = apps.get_model('facebookbot', 'FacebookPage')
    TwitterPage = apps.get_model('twitterbot', 'TwitterPage')
    mypool = None
    for t in MemeTemplate.objects.filter(image_pool=None):
        if not mypool:
            mypool = MemeImagePool.objects.get_or_create(name='global templates')[0]
        t.image_pool = mypool
        t.save()
    for c in list(DiscordChannel.objects.all()) + list(FacebookPage.objects.all()) + list(TwitterPage.objects.all()):
        c.image_pools.add(mypool)


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0081_remove_memeimagepool_friendly_name'),
    ]

    operations = [
        migrations.RunPython(do_stuff)
    ]
