# Generated by Django 2.0 on 2018-04-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0082_auto_20180429_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesourceimage',
            name='image_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeImagePool'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='image_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeImagePool'),
        ),
    ]
