# Generated by Django 2.0 on 2018-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0084_auto_20180430_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeimagepool',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
