# Generated by Django 2.0 on 2018-05-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0085_auto_20180502_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesourceimage',
            name='quartile',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='memetemplate',
            name='quartile',
            field=models.IntegerField(default=1),
        ),
    ]
