# Generated by Django 2.0 on 2018-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0086_auto_20180503_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeimagepool',
            name='friendly_name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='memeimagepool',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='memesourceimage',
            name='friendly_name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='memetemplate',
            name='friendly_name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
        ),
    ]
