# Generated by Django 2.0 on 2018-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0088_auto_20180504_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeimagepool',
            name='sourceimgs_only',
        ),
        migrations.RemoveField(
            model_name='memeimagepool',
            name='templates_only',
        ),
        migrations.AddField(
            model_name='memeimagepool',
            name='pool_type',
            field=models.IntegerField(choices=[(2, 'All'), (0, 'Source images'), (1, 'Templates')], default=2),
        ),
    ]
