# Generated by Django 2.0 on 2018-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0089_auto_20180504_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeimagepool',
            name='friendly_name',
            field=models.CharField(default='', max_length=64, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='memeimagepool',
            name='pool_type',
            field=models.IntegerField(choices=[(2, 'Any'), (0, 'Source images'), (1, 'Templates')], default=2),
        ),
    ]
