# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memeviewer', '0022_auto_20170908_1320'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='DiscordCommand',
            fields=[
                ('cmd', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('help', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Discord command',
            },
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('server_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('prefix', models.CharField(default='!', max_length=8)),
                ('meme_limit_count', models.IntegerField(default=3)),
                ('meme_limit_time', models.IntegerField(default=10)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext')),
            ],
            options={
                'verbose_name': 'Discord server',
            },
        ),
        migrations.AddField(
            model_name='discordcommand',
            name='server_whitelist',
            field=models.ManyToManyField(blank=True, to='discordbot.DiscordServer'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]

