# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordcommand',
            options={'verbose_name': 'Command'},
        ),
        migrations.AlterModelOptions(
            name='discordserver',
            options={'verbose_name': 'Server'},
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='cmd',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='help',
            field=models.TextField(blank=True, null=True, verbose_name='Help string'),
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Text message'),
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='server_whitelist',
            field=models.ManyToManyField(blank=True, to='discordbot.DiscordServer', verbose_name='Server whitelist'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeContext', verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='meme_limit_count',
            field=models.IntegerField(default=3, verbose_name='Meme limit'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='meme_limit_time',
            field=models.IntegerField(default=10, verbose_name='Meme limit cooldown'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='prefix',
            field=models.CharField(default='!', max_length=8, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='server_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
