# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0003_discordmeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommand',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
