# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0004_discordcommand_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmeem',
            name='user_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='User ID'),
        ),
    ]
