# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0005_discordmeem_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Nickname')),
                ('meme_limit_count', models.IntegerField(blank=True, default=None, null=True, verbose_name='Meme limit')),
                ('meme_limit_time', models.IntegerField(blank=True, default=None, null=True, verbose_name='Meme limit timeout')),
            ],
            options={
                'verbose_name': 'Server user',
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='User ID')),
                ('name', models.CharField(max_length=64, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Discord user',
            },
        ),
        migrations.RemoveField(
            model_name='discordmeem',
            name='server',
        ),
        migrations.RemoveField(
            model_name='discordmeem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Server name'),
        ),
        migrations.AddField(
            model_name='discordserveruser',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServer', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='discordserveruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser', verbose_name='Discord user'),
        ),
        migrations.AddField(
            model_name='discordmeem',
            name='server_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordServerUser'),
        ),
    ]
