# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0007_auto_20170919_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServerUserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=64, verbose_name='Permission')),
                ('server_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServerUser', verbose_name='Server user')),
            ],
            options={
                'verbose_name': 'User permission',
            },
        ),
        migrations.AddField(
            model_name='discordcommand',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='discordserveruserpermission',
            unique_together=set([('server_user', 'permission')]),
        ),
    ]
