# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0008_auto_20170920_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserveruserpermission',
            name='allow',
            field=models.BooleanField(default=True, verbose_name='Allow'),
        ),
    ]
