# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0010_auto_20170920_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurphyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=256, verbose_name='Request')),
                ('ask_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date asked')),
                ('processed', models.BooleanField(default=False)),
                ('server_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordServerUser')),
            ],
            options={
                'verbose_name': 'Murphy bot request',
            },
        ),
        migrations.AlterModelOptions(
            name='discordserveruserpermission',
            options={'verbose_name': 'Server user permission'},
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={'verbose_name': 'User'},
        ),
    ]
