# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0014_murphyrequest_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murphyrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='murphyrequest',
            name='accept_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date accepted'),
        ),
        migrations.AlterField(
            model_name='murphyrequest',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date answered'),
        ),
        migrations.AlterField(
            model_name='murphyrequest',
            name='process_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Process start'),
        ),
    ]
