# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0016_auto_20170923_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordmeem',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date sent'),
        ),
    ]
