# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0017_auto_20170923_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='murphyrequest',
            name='related_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.MurphyRequest', verbose_name='Related request'),
        ),
    ]
