# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0019_processedmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurphyFacePic',
            fields=[
                ('channel_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Discord channel ID')),
                ('face_pic', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Face pic')),
            ],
            options={
                'verbose_name': 'Murphy bot face pic',
            },
        ),
        migrations.RemoveField(
            model_name='murphyrequest',
            name='accept_date',
        ),
        migrations.RemoveField(
            model_name='murphyrequest',
            name='answer_date',
        ),
        migrations.RemoveField(
            model_name='murphyrequest',
            name='process_date',
        ),
        migrations.RemoveField(
            model_name='murphyrequest',
            name='related_request',
        ),
        migrations.RemoveField(
            model_name='murphyrequest',
            name='request',
        ),
        migrations.AddField(
            model_name='murphyrequest',
            name='face_pic',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Face pic'),
        ),
        migrations.AddField(
            model_name='murphyrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processed?'),
        ),
        migrations.AddField(
            model_name='murphyrequest',
            name='question',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='murphyrequest',
            name='channel_id',
            field=models.CharField(max_length=32, verbose_name='Discord channel ID'),
        ),
        migrations.AlterField(
            model_name='processedmessage',
            name='process_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date processed'),
        ),
    ]
