# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0020_auto_20170926_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='murphyfacepic',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last used'),
        ),
    ]
