# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0022_auto_20170927_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordpermission',
            name='id',
        ),
        migrations.AlterField(
            model_name='discordpermission',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Permission'),
        ),
    ]
