# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0023_auto_20170927_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommand',
            name='help_params',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='help',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Help string'),
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='message',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Text message'),
        ),
    ]
