# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0024_auto_20170928_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='submit_limit_count',
            field=models.IntegerField(default=10, verbose_name='Submission limit'),
        ),
        migrations.AddField(
            model_name='discordserver',
            name='submit_limit_time',
            field=models.IntegerField(default=300, verbose_name='Submission limit cooldown'),
        ),
        migrations.AddField(
            model_name='discordserveruser',
            name='submit_limit_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Meme limit'),
        ),
        migrations.AddField(
            model_name='discordserveruser',
            name='submit_limit_time',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Meme limit timeout'),
        ),
    ]
