# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0026_discordsourceimgsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordsourceimgsubmission',
            old_name='user',
            new_name='server_user',
        ),
    ]
