# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0028_auto_20170930_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserveruser',
            name='meme_limit_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Meme limit'),
        ),
        migrations.AlterField(
            model_name='discordserveruser',
            name='meme_limit_time',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Meme limit timeout'),
        ),
    ]
