# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0031_auto_20170930_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murphyrequest',
            name='question',
            field=models.CharField(default='', max_length=256, verbose_name='Question'),
        ),
    ]
