# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0032_auto_20170930_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murphyrequest',
            name='question',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Question'),
        ),
    ]
