# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0033_auto_20170930_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserveruser',
            name='submit_limit_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Submission limit'),
        ),
        migrations.AlterField(
            model_name='discordserveruser',
            name='submit_limit_time',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Submission limit timeout'),
        ),
    ]
