# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0034_auto_20170930_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordCommandAlias',
            fields=[
                ('alias', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Alias')),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordCommand', verbose_name='Command')),
            ],
            options={
                'verbose_name': 'Command alias',
            },
        ),
    ]
