# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0035_discordcommandalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='log_channel',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
