# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0036_discordserver_log_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserveruser',
            name='no_edits_log',
            field=models.BooleanField(default=False, verbose_name='Dont log edits'),
        ),
    ]
