# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0037_discordserveruser_no_edits_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserveruser',
            name='no_edits_log',
        ),
    ]
