# Generated by Django 2.0 on 2017-12-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0040_auto_20171227_0123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordserveruserpermission',
            unique_together={('server_user', 'permission')},
        ),
    ]
