# Generated by Django 2.0 on 2017-12-27 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0041_auto_20171227_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Permission')),
            ],
            options={
                'verbose_name': 'Permission',
            },
        ),
        migrations.AlterField(
            model_name='discordserverpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordPerm', verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='discordserveruserpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordPerm', verbose_name='Permission'),
        ),
        migrations.DeleteModel(
            name='DiscordPermission',
        ),
    ]
