# Generated by Django 2.0 on 2017-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0043_auto_20171227_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommand',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
    ]
