# Generated by Django 2.0 on 2017-12-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0044_discordcommand_is_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommand',
            name='custom_perm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordPerm', verbose_name='Permission'),
        ),
    ]
