# Generated by Django 2.0 on 2018-01-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0045_discordcommand_custom_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommand',
            name='denied_message',
            field=models.TextField(blank=True, default='', verbose_name='Access denied message'),
        ),
    ]
