# Generated by Django 2.0 on 2018-02-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0046_discordcommand_denied_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordcommand',
            name='is_control',
        ),
    ]
