# Generated by Django 2.0 on 2018-02-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0047_remove_discordcommand_is_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmeem',
            name='sent_date',
        ),
    ]
