# Generated by Django 2.0 on 2018-02-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0051_auto_20180225_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordcommand',
            name='servers',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='commands',
            field=models.ManyToManyField(blank=True, to='discordbot.DiscordCommand', verbose_name='Commands'),
        ),
    ]
