# Generated by Django 2.0 on 2018-02-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0052_auto_20180225_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordsourceimgsubmission',
            options={'verbose_name': 'Discord source image submission'},
        ),
    ]
