# Generated by Django 2.0 on 2018-02-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0053_auto_20180225_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordserverperm',
            unique_together={('server', 'permission')},
        ),
    ]
