# Generated by Django 2.0 on 2018-02-25 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0054_auto_20180225_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='commands',
        ),
        migrations.AddField(
            model_name='discordcommand',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServer', verbose_name='Server'),
            preserve_default=False,
        ),
    ]
