# Generated by Django 2.0 on 2018-03-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0057_auto_20180227_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordsourceimgsubmission',
            name='server_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServerUser', verbose_name='Server user'),
        ),
        migrations.AlterField(
            model_name='murphyrequest',
            name='server_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServerUser'),
        ),
    ]
