# Generated by Django 2.0 on 2018-03-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0058_auto_20180301_0142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordserveruser',
            unique_together=set(),
        ),
    ]
