# Generated by Django 2.0 on 2018-03-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0059_auto_20180301_0234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordserveruser',
            unique_together={('user', 'server')},
        ),
    ]
