# Generated by Django 2.0 on 2018-03-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0061_auto_20180323_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedMessage',
        ),
        migrations.RemoveField(
            model_name='discordserveruser',
            name='meme_limit_count',
        ),
        migrations.RemoveField(
            model_name='discordserveruser',
            name='meme_limit_time',
        ),
        migrations.AddField(
            model_name='discordserveruser',
            name='unlimited_memes',
            field=models.BooleanField(default=False, verbose_name='Unlimited memes'),
        ),
    ]
