# Generated by Django 2.0 on 2018-03-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0062_auto_20180323_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserveruser',
            name='meme_count',
            field=models.IntegerField(default=0, verbose_name='Generated memes'),
        ),
        migrations.AddField(
            model_name='discordserveruser',
            name='submission_count',
            field=models.IntegerField(default=0, verbose_name='Submitted source images'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='meme_count',
            field=models.IntegerField(default=0, verbose_name='Generated memes'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='submission_count',
            field=models.IntegerField(default=0, verbose_name='Submitted source images'),
        ),
    ]
