# Generated by Django 2.0 on 2018-03-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0065_auto_20180323_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordmeem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discordsourceimgsubmission',
            options={},
        ),
        migrations.AlterField(
            model_name='discordmeem',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem'),
        ),
        migrations.AlterField(
            model_name='discordsourceimgsubmission',
            name='server_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServerUser'),
        ),
        migrations.AlterField(
            model_name='discordsourceimgsubmission',
            name='sourceimg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeSourceImage'),
        ),
    ]
