# Generated by Django 2.0 on 2018-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0066_auto_20180323_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='user_count',
            field=models.IntegerField(default=0, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='server_count',
            field=models.IntegerField(default=0, verbose_name='Servers'),
        ),
    ]
