# Generated by Django 2.0 on 2018-03-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0067_auto_20180323_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserveruser',
            name='nickname',
        ),
    ]
