# Generated by Django 2.0 on 2018-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0069_auto_20180323_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordcommand',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discordcommand',
            name='cmd',
            field=models.CharField(max_length=32, verbose_name='Command'),
        ),
        migrations.AlterUniqueTogether(
            name='discordcommand',
            unique_together={('server', 'cmd')},
        ),
        migrations.AddIndex(
            model_name='discordcommand',
            index=models.Index(fields=['server', 'cmd'], name='idx_discordcmd'),
        ),
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['context'], name='idx_ds_context'),
        ),
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['submission_count'], name='idx_ds_scount'),
        ),
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['meme_count'], name='idx_ds_mcount'),
        ),
        migrations.AddIndex(
            model_name='discordserveruser',
            index=models.Index(fields=['user', 'server'], name='idx_ds_user'),
        ),
        migrations.AddIndex(
            model_name='discorduser',
            index=models.Index(fields=['name'], name='idx_du_name'),
        ),
        migrations.AddIndex(
            model_name='discorduser',
            index=models.Index(fields=['submission_count'], name='idx_du_scount'),
        ),
        migrations.AddIndex(
            model_name='discorduser',
            index=models.Index(fields=['meme_count'], name='idx_du_mcount'),
        ),
    ]
