# Generated by Django 2.0 on 2018-03-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0070_auto_20180324_1528'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['name'], name='idx_ds_name'),
        ),
    ]
