# Generated by Django 2.0 on 2018-03-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0071_auto_20180324_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='meme_limit_count',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='meme_limit_time',
        ),
        migrations.RemoveField(
            model_name='discordserveruser',
            name='unlimited_memes',
        ),
    ]
