# Generated by Django 2.0 on 2018-04-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0072_auto_20180331_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmeem',
            name='discord_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordUser'),
        ),
        migrations.AddField(
            model_name='discordsourceimgsubmission',
            name='discord_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser'),
        ),
        migrations.AlterField(
            model_name='discordmeem',
            name='server_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordServerUser'),
        ),
        migrations.AlterField(
            model_name='discordsourceimgsubmission',
            name='server_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordServerUser'),
        ),
    ]
