# Generated by Django 2.0 on 2018-04-22 22:33

from django.db import migrations


def fill_users_and_servers(apps, _):
    dmeems = apps.get_model('discordbot', 'DiscordMeem')
    for dmeem in dmeems.objects.all():
        if dmeem.server_user:
            dmeem.discord_user = dmeem.server_user.user
            dmeem.discord_server = dmeem.server_user.server
            dmeem.save()

    dsubs = apps.get_model('discordbot', 'DiscordSourceImgSubmission')
    for dsub in dsubs.objects.all():
        if dsub.server_user:
            dsub.discord_user = dsub.server_user.user
            dsub.discord_server = dsub.server_user.server
            dsub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0075_auto_20180423_0058'),
    ]

    operations = [
        migrations.RunPython(fill_users_and_servers)
    ]
