# Generated by Django 2.0 on 2018-04-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0079_auto_20180427_2257'),
        ('discordbot', '0076_auto_20180423_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('channel_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('recent_image', models.TextField(blank=True, default='')),
                ('blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='discordserver',
            options={'verbose_name': 'Server'},
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='discordserver',
            name='idx_ds_context',
        ),
        migrations.RemoveIndex(
            model_name='discordserver',
            name='idx_ds_scount',
        ),
        migrations.RemoveIndex(
            model_name='discordserver',
            name='idx_ds_mcount',
        ),
        migrations.RemoveIndex(
            model_name='discorduser',
            name='idx_du_scount',
        ),
        migrations.RemoveIndex(
            model_name='discorduser',
            name='idx_du_mcount',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='meme_count',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='submission_count',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='user_count',
        ),
        migrations.RemoveField(
            model_name='discordsourceimgsubmission',
            name='discord_server',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='meme_count',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='server_count',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='submission_count',
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='discordsourceimgsubmission',
            name='discord_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordUser'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='user_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DiscordCommand',
        ),
        migrations.DeleteModel(
            name='DiscordServerUser',
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='image_pools',
            field=models.ManyToManyField(to='memeviewer.MemeImagePool'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='recent_template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memeviewer.MemeTemplate'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordServer'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='submission_pool',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_channel', to='memeviewer.MemeImagePool'),
        ),
        migrations.AddField(
            model_name='discordmeem',
            name='discord_channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordChannel'),
        ),
        migrations.AddField(
            model_name='discordsourceimgsubmission',
            name='discord_channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordChannel'),
        ),
        migrations.AddIndex(
            model_name='discordchannel',
            index=models.Index(fields=['name'], name='idx_dc_name'),
        ),
        migrations.AddIndex(
            model_name='discordchannel',
            index=models.Index(fields=['server'], name='idx_dc_server'),
        ),
    ]
