# Generated by Django 2.0 on 2018-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0080_auto_20180428_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='disabled_cmds',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='discordserver',
            name='disabled_cmds',
            field=models.TextField(blank=True, default=''),
        ),
    ]
