# Generated by Django 2.0 on 2018-04-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeviewer', '0084_auto_20180430_2315'),
        ('discordbot', '0082_discordserver_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeImagePoolOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_requested', models.BooleanField(default=False)),
                ('image_pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.MemeImagePool')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discordbot.DiscordUser')),
                ('shared_with', models.ManyToManyField(related_name='shared_image_pool', to='discordbot.DiscordUser')),
            ],
        ),
    ]
