# Generated by Django 2.0 on 2018-04-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0083_memeimagepoolownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeimagepoolownership',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_image_pool', to='discordbot.DiscordUser'),
        ),
    ]
