# Generated by Django 2.0 on 2018-04-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0084_auto_20180501_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeimagepoolownership',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_image_pool', to='discordbot.DiscordUser'),
        ),
    ]
