# Generated by Django 2.0 on 2018-05-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0085_memeimagepoolownership_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeimagepoolownership',
            name='publish_requested',
            field=models.NullBooleanField(default=None),
        ),
    ]
