# Generated by Django 2.0 on 2018-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0086_auto_20180501_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeimagepoolownership',
            name='publish_requested',
        ),
        migrations.AddField(
            model_name='memeimagepoolownership',
            name='status',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Pending approval'), (2, 'Private (Rejected)'), (3, 'Public')], default=0),
        ),
    ]
