# Generated by Django 2.0 on 2018-05-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0087_auto_20180503_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordChannel')),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discordbot.DiscordUser')),
            ],
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='discord_users',
            field=models.ManyToManyField(through='discordbot.DiscordChannelUser', to='discordbot.DiscordUser'),
        ),
    ]
