# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memeviewer', '0024_auto_20170908_1445'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='TwitterMeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=40, verbose_name='Post link')),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem', verbose_name='Meme link')),
            ],
            options={
                'verbose_name': 'Twitter meme link',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
