# Generated by Django 2.0 on 2018-04-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0003_auto_20180428_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittermeem',
            name='meme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem'),
        ),
    ]
