# Generated by Django 2.0 on 2018-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterbot', '0004_auto_20180428_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpage',
            name='handle',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
