# Generated by Django 2.0 on 2018-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookbot', '0003_auto_20180428_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='app_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='app_secret',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
