# Generated by Django 2.0 on 2018-04-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebookbot', '0004_auto_20180428_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookmeem',
            name='meme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memeviewer.Meem'),
        ),
    ]
