# Generated by Django 2.0 on 2018-04-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookbot', '0005_auto_20180428_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='app_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='app_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
