# Generated by Django 2.2.2 on 2019-06-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookbot', '0006_auto_20180429_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='facebookpage',
            name='app_secret',
        ),
    ]
