from django.conf import settings

BASE_DIR = settings.BASE_DIR
DEBUG = settings.DEBUG

DISCORD_TOKEN = settings.DISCORD_TOKEN
DISCORD_STATUS = settings.DISCORD_STATUS

MEEM_MAX_SRCIMG_SIZE = settings.MEEM_MAX_SRCIMG_SIZE
MEEM_LIMIT = settings.MEEM_LIMIT
MEEM_COOLDOWN = settings.MEEM_COOLDOWN

DANCE_LIMIT = settings.DANCE_LIMIT
DANCE_COOLDOWN = settings.DANCE_COOLDOWN
DANCE_MAX_LEN = settings.DANCE_MAX_LEN
DANCE_MAX_W = settings.DANCE_MAX_W

WEBSITE_URL = settings.WEBSITE_URL
IMAGEMAGICK_PATH = settings.IMAGEMAGICK_PATH
