from django.conf import settings

DEBUG = settings.DEBUG

OAUTH2_CLIENT_ID = settings.OAUTH2_CLIENT_ID
OAUTH2_CLIENT_SECRET = settings.OAUTH2_CLIENT_SECRET
OAUTH2_REDIRECT_URI = settings.OAUTH2_REDIRECT_URI
OAUTH2_TOKEN_URL = settings.OAUTH2_TOKEN_URL
OAUTH2_REVOKE_URL = settings.OAUTH2_REVOKE_URL

MEEM_MAX_SRCIMG_SIZE = settings.MEEM_MAX_SRCIMG_SIZE

WEBSITE_URL = settings.WEBSITE_URL
BOT_INVITE_URL = settings.BOT_INVITE_URL

DISCORD_API_ROOT = settings.DISCORD_API_ROOT
